### ISSUE TITLE
Pre-release changes still not working [Bug]

### ISSUE THREAD

**Issue by bayssmekanique** [EndBug/version-check#158]
**Describe the bug**
Using the `diff-search: true` option, pre-release changes are not properly detected.

**To Reproduce**
Moving from `"version": "2.5.0-beta.0"` to `"version": "2.5.0-beta.1"` in the `package.json` file results in the following output:
```
Run EndBug/version-check@v[2](https://github.com/KeiserCorp/Keiser.A500.Display.Main/runs/6068099586?check_suite_focus=true#step:4:2)
  with:
    diff-search: true
    token: ***
    file-name: package.json
    github-api-url: https://api.github.com
Searching for version update...
Searching in 1 commit...
  Package file name: "package.json"
  Package file URL: undefined
  Version assumptions: undefined
No standard npm version commit found, switching to diff search (this could take more time...)
Checking the diffs of 1 commit...
  - 97615[4](https://github.com/KeiserCorp/Keiser.A500.Display.Main/runs/6068099586?check_suite_focus=true#step:4:4)7: added version doesn't match current one (added: "2.[5](https://github.com/KeiserCorp/Keiser.A500.Display.Main/runs/6068099586?check_suite_focus=true#step:4:5).0-beta"; current: "2.5.0-beta.1")
No matching commit found.

Outputs:
  changed: false
```

**Expected behavior**
Should result in `changed: true`.

**Additional details**
While digging for this issue I came to lines 394-396 of the `main.ts` file where I suspect the issue resides, though I don't know the output of the included package to determine if this is indeed the issue.
https://github.com/EndBug/version-check/blob/0a4902241888a3acf7fa6d959a7be7182732b0c2/src/main.ts#L394-L396

**Comment by SwabianCoder** [comment]
Wanted to use your GitHub action in my GitHub worflow. Unfortunately I'm facing the same issue.

**Comment by SwabianCoder** [comment]
As a workaround I use pysemver CLI now. Works great with pre-release versions as well.

**Comment by SwabianCoder** [comment]
> **Describe the bug**
> 
> Using the `diff-search: true` option, pre-release changes are not properly detected.
> 
> 
> 
> **To Reproduce**
> 
> Moving from `"version": "2.5.0-beta.0"` to `"version": "2.5.0-beta.1"` in the `package.json` file results in the following output:
> 
> ```
> 
> Run EndBug/version-check@v[2](https://github.com/KeiserCorp/Keiser.A500.Display.Main/runs/6068099586?check_suite_focus=true#step:4:2)
> 
>   with:
> 
>     diff-search: true
> 
>     token: ***
> 
>     file-name: package.json
> 
>     github-api-url: https://api.github.com
> 
> Searching for version update...
> 
> Searching in 1 commit...
> 
>   Package file name: "package.json"
> 
>   Package file URL: undefined
> 
>   Version assumptions: undefined
> 
> No standard npm version commit found, switching to diff search (this could take more time...)
> 
> Checking the diffs of 1 commit...
> 
>   - 97615[4](https://github.com/KeiserCorp/Keiser.A500.Display.Main/runs/6068099586?check_suite_focus=true#step:4:4)7: added version doesn't match current one (added: "2.[5](https://github.com/KeiserCorp/Keiser.A500.Display.Main/runs/6068099586?check_suite_focus=true#step:4:5).0-beta"; current: "2.5.0-beta.1")
> 
> No matching commit found.
> 
> 
> 
> Outputs:
> 
>   changed: false
> 
> ```
> 
> 
> 
> **Expected behavior**
> 
> Should result in `changed: true`.
> 
> 
> 
> **Additional details**
> 
> While digging for this issue I came to lines 394-396 of the `main.ts` file where I suspect the issue resides, though I don't know the output of the included package to determine if this is indeed the issue.
> 
> https://github.com/EndBug/version-check/blob/0a4902241888a3acf7fa6d959a7be7182732b0c2/src/main.ts#L394-L396

Also ’1.0.0-beta.0’ should be detected to be smaller as ’1.0.0-rc.0’. Current behavior is that both versions are detected to be equal.

**Comment by HarelM** [comment]
I have the same issue.
I'm using this action and just released 4.0.0-pre.1 and I got this log:
```
Run EndBug/version-check@v2
  with:
    diff-search: false
    file-name: package.json
    token: ***
    github-api-url: https://api.github.com
Searching for version update...
Searching in 1 commit...
  Package file name: "package.json"
  Package file URL: undefined
  Version assumptions: undefined
No standard npm version commit found, switching to diff search (this could take more time...)
Checking the diffs of 1 commit...
  - 08[4](https://github.com/maplibre/maplibre-gl-js/actions/runs/6968190440/job/18961591361#step:4:4)ef[5](https://github.com/maplibre/maplibre-gl-js/actions/runs/6968190440/job/18961591361#step:4:5)[6](https://github.com/maplibre/maplibre-gl-js/actions/runs/6968190440/job/18961591361#step:4:6): added version doesn't match current one (added: "4.0.0"; current: "4.0.0-pre.1")
No matching commit found.
Outputs:
  changed: false
```

@SwabianCoder how did you solve this?

This is my workflow file:
https://github.com/maplibre/maplibre-gl-js/blob/084ef56ccd357d280ededd194370fc85181f3f43/.github/workflows/release.yml#L26

**Comment by SwabianCoder** [comment]
@HarelM I use pysemver CLI to compare versions. This works great.

**Comment by HarelM** [comment]
Can you link to a GitHub action with this?

**Comment by SwabianCoder** [comment]
Sure: https://github.com/SwabianCoder/ngx-toolset/blob/main/.github/workflows/pr_validation.yml

**Comment by HarelM** [comment]
Thanks @SwabianCoder!! I have switched to a very basic comparison based on your code. See the above linked PR.

**Comment by SwabianCoder** [comment]
@HarelM But based on that comparison you can't determine whether version increased. What if someone decreased it instead?

**Comment by HarelM** [comment]
Yes, that's true, but every PR is reviewed before merged, and we have branch protection, so I hope it's good enough, worst case I'll improve it later on, I needed to release a pre release, this was my number one goal...

**Comment by kusyka911** [comment]
@EndBug 
Issue still exists for `static-checking`. Mostly because of using `semver-regex`.
Using it on prerelease versions like `1.0.0-beta.1` will reuslt in `1.0.0`.
And you are comparing versions from remote and local `package.json` files after matching it with `semver-regex`.

Lines 100-104 at [src/main.ts](https://github.com/EndBug/version-check/blob/v2.1.1/src/main.ts#l101)
```typescript
    if (
      (local.match(semverRegex()) || [])[0] !=
      (remote.match(semverRegex()) || [])[0]
    ) {
```

See codesandbox demo here: [https://codesandbox.io/p/devbox/interesting-euclid-4wkr5g](https://codesandbox.io/p/devbox/interesting-euclid-4wkr5g)

**Comment by EndBug** [comment]
This issue should be fixed by the awesome work by @kusyka911 🎉 
I'll publish it right away!

**Comment by EndBug** [comment]
@all-contributors
add @bayssmekanique for bug
add @SwabianCoder for bug

**Comment by EndBug** [comment]
@all-contributors please add @SwabianCoder for bug

**Comment by HarelM** [comment]
Is it possible to add to the readme the possible values of `type` after this fix?
Is there a way for me to know that this is a pre-release using this action?

**Comment by EndBug** [comment]
@HarelM Good point, I should mention in the docs that the definition of the type is dependent on the [`semver-diff`](https://www.npmjs.com/package/semver-diff) package

**Comment by EndBug** [comment]
@all-contributors please add @HarelM for their docs contribution
