### ISSUE TITLE
What permissions are need for this action

### ISSUE THREAD

**Issue by jchandramouli** [EndBug/version-check#236]
Recently we applied permissions to a job using this action and it started failing with 403 error

```
Error: Request failed with status code 403
```
Can you please let us know the permissions required for this job per this github actions permissions [link](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs)

Thank you

**Comment by EndBug** [comment]
Hi, if the repo is public, can you send me a link to the failing workflow run? And if the repo is private, can you send me the logs of the step that uses the action?
Thanks

**Comment by jchandramouli** [comment]
I figured it. These permissions are needed for the `version-check` action
```
contents: read 
pull-requests: read
```
