### ISSUE TITLE
try catch of JSON.parse swallowed possible errors

### ISSUE THREAD

**Issue by CJY0208** [EndBug/version-check#25]
Hi, I’m here again, I found a question about the error message

Today I keep getting the following error message when using the remote version check

> Couldn't find remote version.

This error prompt made me spend some time checking the connectivity of remote files, and even suspected that there was a link problem between the github server and the unpkg server.

Until I temporarily turned off the version check function, I discovered that the `package.json` file of my local warehouse had a syntax error.

> ...react-router-cache-route/package.json: Unexpected token] in JSON at position 351

I noticed that the `JSON.parse` part of [version-check/src/main.ts](https://github.com/EndBug/version-check/blob/master/src/main.ts#L78) was wrapped with `try catch`, but it didn’t throw out the problem, and swallowed possible errors in the parsing process

https://github.com/EndBug/version-check/blob/7d67b971df2c119e8dab599b302b311d5db2e8f7/src/main.ts#L78-L87

My suggestion is to throw the error so that I can discover my stupid problem in time >_<

**Comment by CJY0208** [comment]
Here are the actions that confuse me:

- https://github.com/CJY0208/react-router-cache-route/actions/runs/257764334
- https://github.com/CJY0208/react-router-cache-route/actions/runs/257746899
- https://github.com/CJY0208/react-router-cache-route/actions/runs/257746899

Here is  the action that indicate the real error:

- https://github.com/CJY0208/react-router-cache-route/actions/runs/257769745

**Comment by EndBug** [comment]
Hi, I've pushed a fix to the master branch: now when there's an error while parsing the package file it will be logged, even though it will not cause the action to fail (it will fail as usual with a user-friendly error)
Give it a try and let me know if that works for you ;)

**Comment by CJY0208** [comment]
Hello, 

I am trying with the same mistack using `version-check@master` 

```json5
// package.json
{
  ...
  "keywords": [
    "cache",
    "cache route",
    "keep alive",
    "react",
    "react router",
    "keep alive route", // <------- An extra comma makes an invaild JSON format
  ],
 ...
}
```

And then recived an unclear error tips

>  ##[error](e || "").replace is not a function

Seems to be the question from `@actions/core/error`

**Comment by EndBug** [comment]
Ok, I've pushed a second fix. Would you please try again?
