### ISSUE TITLE
[Feature] Add pre-release output

### ISSUE THREAD

**Issue by HarelM** [EndBug/version-check#268]
**Is your feature request related to a problem? Please describe.**
Currently, we have some code in our CI that checks around pre-release (in general, not just premajor, preminor, etc).
It would be cool to be able to remove this code and use this version check.

**Describe the solution you'd like**
An `boolean` output called `prerelease` which is either `true` or `false` according to the current version.

**Describe alternatives you've considered**
We are using semver's prerelease method, it's OK, but I would prefer to use an action instead.

**Additional context**
This is in continue to the following issue #158.

Here's our CI code:
https://github.com/maplibre/maplibre-gl-js/blob/bb219f0cc9046032b71fddc9fc59d10471bf97e3/.github/workflows/release.yml#L64

It would be nice to remove some dependencies such as `martinbeentjes/npm-get-version-action` and other steps and simply using this action.

Thanks!

**Comment by EndBug** [comment]
Hey, when the change is a prerelease the `type` output of this action should be `prerelease`
Is that not happening? 👀

**Comment by HarelM** [comment]
I haven't fully tested this, but according to the link docs there is preminor, premajor and prepatch which I think are basically the same as prerelease.

**Comment by EndBug** [comment]
Kinda, even though they are different. I guess it depends on the context you're using this action in :/
If you want some further reading, check out the docs of npm/node-semver (npm's semver parser, that is used by library I'm using to get the diff)
- https://github.com/npm/node-semver?tab=readme-ov-file#prerelease-tags
- https://github.com/npm/node-semver?tab=readme-ov-file#functions

**Comment by HarelM** [comment]
Yea, I guess it is, in any case, feel free to close this issue.
My use case is that I only care if it's a regular release (major, minor, patch) or something else in my action, so I need to take care of this situation differently.
I'm currently using semver's `prerelease` method to simplify this check, but I would like to remove some complexity in the build by using this action, but I need this destiction.
