### ISSUE TITLE
Possible to use local?

### ISSUE THREAD

**Issue by yaneony** [EndBug/version-check#289]
Is it possible to check local version of package, commit changes without involving some npm registry and doing http request?

**Comment by EndBug** [comment]
Look into the `static-checking` option ;)

**Comment by yaneony** [comment]
> You can use this option to make the action check the local version against the remote one (from the provided URL, see the `file-url` option).
As I understand, that option is for checking remote->local and local->remote. I'm looking for local->local. Or I'm getting it wrong?

**Comment by EndBug** [comment]
@yaneony True local to local comparison is not present in this action at the moment. 
You can play with the `file-url` input if you need something like checking the version before the current push (`::before`), or checking from a specific commit on GitHub (using the raw file URL, works from any (public) repo)
