### ISSUE TITLE
Unable to detect a version change

### ISSUE THREAD

**Issue by db5rg3ss** [EndBug/version-check#32]
Hey guys..

I want to use your action to detect the version change of a sub-component...  an npm package.  So I was using the file-name property to set the location of my package.json.   I am finding that I never get a positive result.. even when I have explicitly upped the version just for testing using npm version patch.  I am running the workflow on every push.  Here is the result of the action:

Run EndBug/version-check@v1
  with:
    file-name: ./sdk/package.json
Searching for version update...
Searching in 1 commit...
  Package file name: "sdk/package.json"
  Package file URL: undefined
  Version assumptions: undefined

No matching commit found.

Not sure what I am doing wrong.

**Comment by EndBug** [comment]
Is this on a public repo? If so, can you give me a link to the workflow run you're referring to?

**Comment by db5rg3ss** [comment]
Sorry.. no its a private repo.

**Comment by EndBug** [comment]
Have you tried using the [`diff-search` option](https://github.com/EndBug/version-check#usage)?

**Comment by db5rg3ss** [comment]
Just tried...  I get an error in that case...

Searching in 1 commit...
  Package file name: "sdk/package.json"
  Package file URL: undefined
  Version assumptions: undefined
No standard npm version commit found, switching to diff search (this could take more time...)
Checking the diffs of 1 commit...
  Error: An error occurred in checkDiff:
  Error: Request failed with status code 404
  Error: Error: Command failed with code 1

**Comment by EndBug** [comment]
That's because you're running it on a private repo without the `token` option

**Comment by db5rg3ss** [comment]
AWESOME!  That worked..  Thanks for your help guys..

**Comment by EndBug** [comment]
You're welcome. I'll close the issue for now
