### ISSUE TITLE
[Bug] Unexpected version update detecting in "update from main branch" commits not in a final diff

### ISSUE THREAD

**Issue by talyguryn** [EndBug/version-check#39]
**Describe the bug**

 Is there any way to check for a version update in the final pr diff, not in every commits?

i use this action to detect a version update after pull request merge for creating a bump version pr if it is required. so i need to check if pull request's diff only not a single commit. so if i pull changes from main branch (with any version bump) to the branch which im working on i will get a "version was updated" flag after merging this branch back to the main even if diff has no version changes. Am i doing it right?

```
main 
  | \
  |  my-branch
  *<---------------- commit with a version update
  | \|
  |  * update from main
  |  |
  | /
  * merge my-branch into main
  |
```

After this steps i will get a "version was updated" but it does not. 

**To Reproduce**

1. Create a branch `my-branch` from `main`
2. Push version update to the `main`
3. Pull changes from 'main' to `my-branch`
4. Push changes from `my-branch` to `main`
5 .Check for a version update. It should return `true`

**Expected behavior**

By the diff there is version update so i need to get "version was not updated"

**Screenshots**

PR commits:

![image](https://user-images.githubusercontent.com/15259299/108963571-5562c480-768b-11eb-95b5-9d0bae25c1ff.png)

Changes:

![image](https://user-images.githubusercontent.com/15259299/108963677-79bea100-768b-11eb-9f1c-093a2fca2fb9.png)

Action logs:

![image](https://user-images.githubusercontent.com/15259299/108963641-6dd2df00-768b-11eb-890a-ba4b08612cf0.png)

**Additional context**

My actions:
- [bump-version-on-merge-next](https://github.com/talyguryn/editor.js/blob/next/.github/workflows/bump-version-on-merge-next.yml)
- [create-release-draft](https://github.com/talyguryn/editor.js/blob/next/.github/workflows/create-release-draft.yml)

**Comment by talyguryn** [comment]
well, i have found a solution. need to get current package version after merge and package version in repo before merge.

https://github.com/codex-team/editor.js/blob/254a94e81212af294a87d0fd6cc13647c32b65ad/.github/workflows/bump-version-on-merge-next.yml#L11-L40

but it does not resolve issue

**Comment by EndBug** [comment]
Hi, I'm not sure if I get the problem right, but here's what I think:
The action works using commits because that's what is provided by GitHub and it's somewhat reliable. Checking the overall changes can modify the action's behavior, and so I'd prefer to keep it that way. 

The solution you ended up with seems pretty fine to me. If you want to add the "check PR diff" option to this action, feel free to a PR, I'll be very happy to review it :)
