### ISSUE TITLE
[Feature] Add support for private repos

### ISSUE THREAD

**Issue by EndBug** [EndBug/version-check#8]
As pointed out by @sergeyzwezdin in issue #7 ([comment link](https://github.com/EndBug/version-check/issues/7#issuecomment-544776440)) the action doesn't currently work in private repository.
That's caused by the fact that it does an http call to the GitHub REST API without authentication, and so it's not able to detect private repos.

That could be easily fixable by using the `GITHUB_TOKEN` automatically created for the action as the bearer authorization token, as described [here](https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#github_token-secret)

---

*Original comment:*

> Recently I created private repo and the action didn't work returning the following error:
> 
> > Error: Request failed with status code 404
> 
> Once I converted the repo into public it started working.
> 
> https://github.com/sergeyzwezdin/actions-test/commit/62ce369b5b1334cc8fa23d0a342e833da9aff333/checks?check_suite_id=275117829
> 
> https://github.com/sergeyzwezdin/actions-test/commit/06a578b309174816da3839ab63eb19603ced8620/checks?check_suite_id=275130285
> 
> Is it supposed not to work in private repos?

**Comment by EndBug** [comment]
@sergeyzwezdin You can use your action in a private repo with [`EndBug/version-check@v1.1.0`](https://github.com/EndBug/version-check/releases/tag/v1.1.0)

**Comment by sergeyzwezdin** [comment]
Quite fast! 💪
Thank you!

**Comment by EndBug** [comment]
@all-contributors-bot please add @sergeyzwezdin for ideas

**Comment by EndBug** [comment]
@all-contributors please add @sergeyzwezdin for ideas

**Comment by AlexRex** [comment]
Hey! Regarding private repos, what about using this options: 
```
          static-checking: localIsNew
          file-url: ::before
```
As it will try to download the package.json from a private repo for static-checking it will fail. Is there a way to fix this? I am open to create a PR.
